# DataSource Config
spring:
  application:
    # 应用名称
    name: zymonitor-springboot
  mvc:
    # 静态资源路径
    static-path-pattern: /static/**
  datasource:
    # 数据源名称
    name: druid
    # 数据源类型
    type: com.alibaba.druid.pool.DruidDataSource
    # 数据库驱动：
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库连接地址
    url: jdbc:mysql://localhost:3306/zymonitor?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    # Spring Boot 默认是不注入这些属性值的，需要自己绑定
    # druid 数据源专有配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true

    # 配置监控统计拦截的filters，stat:监控统计、log4j：日志记录、wall：防御sql注入
    # 如果允许时报错  java.lang.ClassNotFoundException: org.apache.log4j.Priority
    # 则导入 log4j 依赖即可，Maven 地址：https://mvnrepository.com/artifact/log4j/log4j
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  thymeleaf:
    # 设置thymeleaf路径默认为src/main/resources/templates
    prefix: classpath:/templates/
    # 设置thymeleaf模板后缀
    suffix: .html
    # 是否开启缓存默认为true
    content-type: text/html
    cache: false
    # 设置thymeleaf严格校验
    mode: HTML
    # 设置编码
    encoding: UTF-8
  redis:
    port: 6379
    host: localhost
    database: 0

server:
  # 应用服务 WEB 访问端口
  port: 8080
mybatis:
  check-config-location: true
  #mybatis配置文件地址
  config-location: classpath:mybatis/mybatis-config.xml
  #mybatisXML文件地址
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.zhongye.zymonitor.bean
logging:
  level:
    root: info